@URLShortener.Api_HostAddress = http://localhost:5070

POST {{URLShortener.Api_HostAddress}}/api/Url/shorten
Content-Type: application/json

{
  "shortUrl": "abc123",
  "longUrl": "https://www.google.com"
}

###
